services:
  clickhouse:
    image: clickhouse/clickhouse-server
    volumes:
      - ./.clickhouse_local_data:/var/lib/clickhouse
      - ./docker/dev.xml:/etc/clickhouse-server/users.d/dev.xml
    ports:
      - "9000:9000"
      - "8123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
