services:
  ch-ui-enhanced:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        PROXY: ${HTTP_PROXY:-}
    restart: always
    ports:
      - "${CH_UI_PORT:-5555}:5521"
    # Optional, provide if you want but not needed
    # environment:
    #   VITE_CLICKHOUSE_URL: "${CLICKHOUSE_URL}"
    #   VITE_CLICKHOUSE_USER: "${CLICKHOUSE_USER}"
    #   VITE_CLICKHOUSE_PASS: "${CLICKHOUSE_PASS}"
