name: 🐞 Bug Report
description: Found something that doesn't work as expected?
body:
  - type: dropdown
    id: Environment
    attributes:
      label: Environment
      description: How are you using CH-UI?
      options:
        - NPM build
        - Docker
        - Other
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: How did you encounter the bug?
      description: How can this bug be reproduced? Please provide steps to reproduce.
      placeholder: |-
        1. Run Docker container... 
        2. npm run build...
        3. Go to...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      description: What it supposed to happen? What did you expect to see?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: What was the accual result?
    validations:
      required: true
  - type: dropdown
    id: Browser
    attributes:
      label: Browser
      description: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Edge
        - Safari
        - Brave
        - Other
    validations:
      required: true
  # browser version with instructions to check it 
  - type: textarea
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser are you using?
      placeholder: e.g. 125.0.0
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of CH-UI are you using?
      placeholder: e.g. 1.5.0
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        ### All done, now, just submit the issue and I will do my best to take care of it!  🙏
    validations:
      required: false
