name: 💡 Feature Request
description: Tell us about something ch-UI doesn't do yet, but should!
body:
  - type: textarea
    id: idea
    attributes:
      label: Idea Statement
      description: Which is the feature you would like to see implemented?
      placeholder: |-
        I want to be able to do anything I want, whenever I want. Because my ideas are the best.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Feature implementation brainstorm
      description: All your ideas are welcome, let's brainstorm together.
      placeholder: |-
        Create the next big feature that will all our problems.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏
    validations:
      required: false
