apiVersion: v2
name: ch-ui
description: CH-UI — a self-hosted ClickHouse management UI
type: application
version: 0.3.1
appVersion: "2.6.2"
home: https://ch-ui.com
sources:
  - https://github.com/caioricciuti/ch-ui
maintainers:
  - name: Caio Ricciuti
    email: me@caioricciuti.com
keywords:
  - clickhouse
  - sql
  - database
  - ui
