name: Deploy CH-UI Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/deploy-docs.yml"

jobs:
  # Check if docs changed
  changes:
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            docs:
              - 'docs/**'
              - '.github/workflows/deploy-docs.yml'

  deploy:
    needs: [changes]
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[skip docs]') &&
      !contains(github.event.head_commit.message, '[skip ci]') &&
      (
        needs.changes.outputs.docs == 'true' ||
        contains(github.event.head_commit.message, '[docs-only]') ||
        contains(github.event.head_commit.message, 'docs-only')
      )
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd docs
          if [ -f "../bun.lock" ]; then
            echo "Using bun to install dependencies"
            bun install
          else
            echo "Using npm to install dependencies"
            npm ci
          fi

      - name: Build website
        run: |
          cd docs
          if [ -f "../bun.lock" ]; then
            echo "Building with bun"
            bun run docs:build
          else
            echo "Building with npm"
            npm run docs:build
          fi

      - name: Add .nojekyll file
        run: touch docs/.vitepress/dist/.nojekyll

      - name: Create CNAME file
        run: echo "ch-ui.com" > docs/.vitepress/dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GHCR_PAT }}
          publish_dir: ./docs/.vitepress/dist
          user_name: ${{ secrets.GIT_USER_NAME }}
          user_email: ${{ secrets.GIT_USER_EMAIL }}