name: Pull Request CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with ${{ matrix.package-manager }}
    strategy:
      matrix:
        package-manager: [bun, npm]
        node-version: [20]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: ${{ matrix.package-manager == 'npm' && 'npm' || '' }}

      - name: Setup Bun
        if: matrix.package-manager == 'bun'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies (Bun)
        if: matrix.package-manager == 'bun'
        run: bun install --frozen-lockfile

      - name: Install dependencies (npm)
        if: matrix.package-manager == 'npm'
        run: npm ci

      - name: Run linter
        run: ${{ matrix.package-manager }} run lint

      - name: Run tests
        run: ${{ matrix.package-manager }} test

      - name: Build application
        run: ${{ matrix.package-manager }} run build

      - name: Check build output
        run: |
          if [ ! -d "dist" ]; then
            echo "❌ Build failed: dist directory not found"
            exit 1
          fi
          echo "✅ Build successful"
          ls -la dist/

  docker-build-test:
    runs-on: ubuntu-latest
    name: Test Docker Build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test standard Dockerfile
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: false
          tags: ch-ui:test-npm
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Bun Dockerfile
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.bun
          platforms: linux/amd64
          push: false
          tags: ch-ui:test-bun
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test images
        run: |
          echo "✅ Docker builds completed successfully"
          docker images | grep ch-ui